apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "benthos.fullname" . }}
  labels:
    {{- include "benthos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "benthos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "benthos.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "benthos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ### For debugging only - enable to allow exec into container
          # command: ["/bin/sh","-c","sleep 300"]
          args:
            - "-c"
            - "/benthos.yaml"
            {{- if eq .Values.watch true}}
            - -w
            {{- end }}
            {{- if and .Values.streams.enabled .Values.streams.streamsConfigMap }}
            - "streams"
            {{- if eq .Values.streams.api.enable false }}
            - "--no-api"
            {{- end }}
            - /streams/*.yaml
            {{- end }}
          ports:
            - name: http
              containerPort: 4195
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
              {{- if .Values.http.tls.enabled }}
              scheme: HTTPS
              {{- end }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
              {{- if .Values.http.tls.enabled }}
              scheme: HTTPS
              {{- end }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.config }}
            - name: config
              mountPath: "/benthos.yaml"
              subPath: "benthos.yaml"
              readOnly: true
            {{- end }}
            {{- if and .Values.http.tls.enabled .Values.http.tls.secretName }}
            - name: tls
              mountPath: "/tls"
              readOnly: true
            {{- end }}
            {{- range .Values.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
            {{- if and .Values.streams.enabled .Values.streams.streamsConfigMap }}
            - name: streams
              mountPath: "/streams"
              readOnly: true
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.config }}
        - name: config
          configMap:
            name: {{ template "benthos.fullname" . }}-config
        {{- end }}
        {{- if and .Values.http.tls.enabled .Values.http.tls.secretName }}
        - name: tls
          secret:
            secretName: {{ .Values.http.tls.secretName }}
        {{- end }}
        {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          {{- if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- end }}
          {{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
          {{- end }}
        {{- end }}
        {{- if and .Values.streams.enabled .Values.streams.streamsConfigMap }}
        - name: streams
          configMap:
            name: {{ .Values.streams.streamsConfigMap }}
        {{- end }}
