{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "benthos.fullname" . }}
  labels:
    {{- include "benthos.labels" . | nindent 4 }}
spec:
{{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
{{- end }}
{{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
{{- end }}
  selector:
    matchLabels:
      {{- include "benthos.selectorLabels" . | nindent 6 }}
{{- end }}