{{- if and .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "benthos.fullname" . }}
  labels:
    {{- include "benthos.labels" . | nindent 4 }}
spec:
  {{- with .Values.serviceMonitor.basicAuth }}
  basicAuth:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval}}
      targetPort: http
      path: /metrics
      scheme: {{ .Values.serviceMonitor.scheme }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "benthos.selectorLabels" . | nindent 6 }}
{{- end }}
